### ISSUE TITLE
Perception tracking isssue

### ISSUE THREAD

**Issue by Sevenfortyseven** [pointfreeco/swift-perception#46]
### Description

Even tho I'm not using @Perception framework and also my view is embedded inside WithPerceptionTracking block, I'm still getting 
`Perceptible state was accessed but is not being tracked. Track changes to state by wrapping your view in a 'WithPerceptionTracking' view.` warning. Warning appears when this view is presented, and it also generates warnings when I enter characters in a textfield and simulator becomes unresponsive. what can be an issue here?
![Screenshot 2024-03-03 at 14 43 43](https://github.com/pointfreeco/swift-perception/assets/86253061/069ceb38-18ae-4469-a5d4-1f42e30b8e30)
![Screenshot 2024-03-03 at 14 44 37](https://github.com/pointfreeco/swift-perception/assets/86253061/bd0224ef-e85f-4f9e-8a47-e550b3852d8b)

### Checklist

- [X] I have determined that this bug is not reproducible using Swift's observation tools. If the bug is reproducible using the `@Observable` macro or another tool from the `Observation` framework, please [file it directly with Apple](https://github.com/apple/swift/issues/new/choose).
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-perception/issues) or [discussion](https://github.com/pointfreeco/swift-perception/discussions).

### Expected behavior

this code to work smoothly

### Actual behavior

I'm getting unexpected warnings and simulator becomes unresponsive while I'm typing in textfield

### Perception version information

main branch

### Destination operating system

iOS 14

### Xcode version information

5.1

**Comment by stephencelis** [comment]
@Sevenfortyseven I'm not sure I understand. Can you zip up an Xcode project that demonstrates the issue and attach it here?

**Comment by mbrandonw** [comment]
Hi @Sevenfortyseven, I'm going to convert this to a discussion for now. Please feel free to share your project in the discussion if you are able to reproduce for us.
